# Generated by Django 4.2.13 on 2026-06-10 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='default_user', max_length=100, unique=True)),
                ('vulnerability_profile', models.TextField(default='User is a new recruit. No history recorded yet. Test their baseline confidence and structure.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('critical_mistake', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='coach.usermemory')),
            ],
        ),
    ]
